ci: use updated syntax
```

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at module.exports (/Users/runner/work/coroutine-scheduler/coroutine-scheduler/node_modules/import-fresh/index.js:32:59)
    at loadJsSync (/Users/runner/work/coroutine-scheduler/coroutine-scheduler/node_modules/cosmiconfig/dist/loaders.js:17:12)
    at loadJs (/Users/runner/work/coroutine-scheduler/coroutine-scheduler/node_modules/cosmiconfig/dist/loaders.js:26:39) {
  filepath: '/Users/runner/work/coroutine-scheduler/coroutine-scheduler/release.config.js'
}
Error: Process completed with exit code 1.
```